---
title: "Covid91 vaccine study Final2024"
author: "Ashley Saunders"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`" 
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
require(forcats)
OldData <-read.csv(file="finalSumr2024.csv",header=TRUE)
#recode to remove the annoying "X" from the dataframe
FinalData <- OldData %>% mutate(infected = recode(infected, covid19 = "covid", none = "OK" )) %>% select(-one_of("X"))
FinalData <- FinalData %>%
mutate(across(where(is.character), as.factor))
FinalData$treatment <- relevel(FinalData$treatment,ref="placebo")
#FinalData$infected <- relevel(FinalData$infected,ref="OK")
Male = filter(FinalData, sex =="M")
Female = filter(FinalData, sex =="F")
Gay = filter(FinalData, LGBTQ =="gay")
DrugUser = filter(FinalData, DrugUser =="yes")
```

# Introduction

A new  preventative vaccine (covid921) is under test in clinical trials. Given the nature of this vaccine it is suspected that the drug may exhibit different effectiveness across the variety of subpopulations tracked. Consider population subgroups by gender( guys and gals), drug use, and sexual orientation. Write a complete report that separately considers this drug for each subgroup and your recommendations as to whether people in the subgroup should take the vaccine. Structure your report in four sections each devoted to one of the four subgroups, use null and alternative hypothesis statements and correct statistical verbage when referencing p-values in conclusions.

## Overall approach

1. **Descriptive Analysis**: Summarize data perceptibly then numerically.
2. **Inferential Analysis**: Perform hypothesis testing:
   - \(H_0\): The vaccine has no impact on infection rates.
   - \(H_A\): The vaccine reduces infection rates.
3. **Effectiveness Calculation**:
   \[
   \text{Vaccine Effectiveness (VE)} = 1 - \frac{\text{Risk}_{\text{vaccine}}}{\text{Risk}_{\text{placebo}}}
   \]
4. **Effectivness Confidence Interval**: low to high

## Males


## Females


## LGBTQ



## Druggies


# Overall Results and Conclusions